name: Gem push

on:
  release:
    types: [published]

jobs:
  github:
    name: Build + Publish to GitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.0.0
      uses: actions/setup-ruby@v1
      with:
        version: 3.0.0
    - name: Publish to GitHub
      uses: jstastny/publish-gem-to-github@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: standout

  rubygems:
    name: Build + Publish to Rubygems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0.0
      uses: actions/setup-ruby@v1
      with:
        version: 3.0.0
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}